### PR TITLE
Added support for reader conditional files (cljc)

### PR DESCRIPTION
**Pull request by sfnelson**
Clojure 1.7.0 will add support for reader conditionals which means that clojure tooling will soon need to be able to deal with namespaces defined in `cljc` files in addition to `clj` files. This patch adds support for resolving namespaces in `cljc` files while maintaining external API compatibility with the previous version.

While similar to Raynes/bultitude#27, this patch also adds an optional "extension" parameter to `path-for`, and fixes the *invalid-namespace* test which seems to have been broken for some time. As a consequence of making this test more robust, it doesn't pass on Clojure 1.2, but this is probably no big loss.

I'm very eager to see this patch merged so that leiningen can be updated to support reader conditionals (https://github.com/technomancy/leiningen/issues/1827). Please let me know if there's anything I can do to help that happen.

### CODE REVIEW

**Comment by Raynes** [comment]
Packed, signed, and sealed.

:ship:

**Comment by sfnelson** [comment]
Awesome, thanks.

**Comment by sfnelson** [comment]
I can't see the 0.2.7 release on clojars, could you please check that you released 0.2.7 rather than 0.2.8-SNAPSHOT?

https://clojars.org/bultitude

**Comment by Raynes** [comment]
Yup, I suck. Fixed.

**Pull request merged**
